apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mesh-node-ws
  name: mesh-node-ws
spec:
  selector:
    matchLabels:
      app: mesh-node-ws
  replicas: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
        prometheus.io/path: '/metrics'
      labels:
        app: mesh-node-ws
    spec:
      containers:
      - image: rammaddali/node-ws:latest
        imagePullPolicy: Always
        name: mesh-node-ws
        ports:
         - name: socket-port
           containerPort: 80