---
apiVersion: v1
kind: Namespace
metadata:
  name: node-ws-alb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: node-ws-alb
  name: node-ws
spec:
  selector:
    matchLabels:
      app: node-ws
  replicas: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
        prometheus.io/path: '/metrics'
      labels:
        app: node-ws
    spec:
      containers:
      - image: {{IMAGE_REPO}}/node-ws:latest
        imagePullPolicy: Always
        name: node-ws
        ports:
         - name: socket-port
           containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-ws
  namespace: node-ws-alb
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: node-ws
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP