apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
    mesh: apps
    gateway: ingress-gw
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: apps
spec:
  namespaceSelector:
    matchLabels:
      mesh: apps